name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v8
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud scanner
        uses: actions/cache@v4 
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}
          restore-keys: sonar-

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sharonct
            -Dsonar.projectKey=sharonct_Pdf_Data_Extraction
